### ISSUE TITLE
Element is not clickable problem 

### ISSUE THREAD

**Issue by mehmetfurkanaydin** [szydan/eeg#10]
![problem](https://cloud.githubusercontent.com/assets/15969928/18270743/78a89ddc-7426-11e6-8fc0-931b29b690b5.jpg)

When checkbox in behind, they're not clickable

**Comment by szydan** [comment]
Published new version 1.0.27 
With new option 
layersOrder: ['legend', 'links','linksLabelsBack','linksLabels', 'nodes'],

This option allow you to control the layers order so you can control which elements are on top and which are on the bottom
